from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


SNAPSHOTS_FILE = "historical_forecast_snapshots.csv"
REALIZED_FILE = "historical_realized_returns.csv"
FEATURE_STORE_FILE = "historical_feature_store.csv"
DATA_QUALITY_FILE = "historical_data_quality_report.csv"
PRODUCTION_PARITY_DAILY_FILE = "production_parity_growth_daily_returns.csv"
GROWTH_TRADES_FILE = "production_parity_growth_trades.csv"
CEDEAR_MAP_FILE = "model_ticker_to_cedear_map.csv"

OUT_DEPENDENCY = "growth_feature_dependency_audit.csv"
OUT_RECONSTRUCT = "growth_reconstructability.csv"
OUT_COVERAGE = "historical_data_coverage.csv"
OUT_PLAN = "growth_reconstruction_plan.csv"
OUT_GOVERNANCE = "growth_reconstruction_governance.csv"

REQUESTED_STARTS = ["2008-01-01", "2010-01-01", "2015-01-01", "2020-01-01"]


def _read_csv(path: str | Path) -> pd.DataFrame:
    p = Path(path)
    if not p.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(p)
    except Exception:
        return pd.DataFrame()


def _dates(df: pd.DataFrame, col: str = "date") -> pd.DataFrame:
    if df.empty or col not in df.columns:
        return df
    out = df.copy()
    out[col] = pd.to_datetime(out[col], errors="coerce").dt.normalize()
    return out.dropna(subset=[col]).sort_values(col)


def _num(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan)


def _date_minmax(df: pd.DataFrame, col: str = "date") -> tuple[pd.Timestamp | pd.NaT, pd.Timestamp | pd.NaT]:
    df = _dates(df, col)
    if df.empty:
        return pd.NaT, pd.NaT
    return df[col].min(), df[col].max()


def _source_date_range(path: str, col: str = "date") -> tuple[str, str]:
    df = _read_csv(path)
    start, end = _date_minmax(df, col)
    return (
        start.strftime("%Y-%m-%d") if pd.notna(start) else "",
        end.strftime("%Y-%m-%d") if pd.notna(end) else "",
    )


def _component_rows() -> list[dict[str, object]]:
    snap_start, snap_end = _source_date_range(SNAPSHOTS_FILE)
    realized_start, realized_end = _source_date_range(REALIZED_FILE)
    feature_start, feature_end = _source_date_range(FEATURE_STORE_FILE)
    parity_start, parity_end = _source_date_range(PRODUCTION_PARITY_DAILY_FILE)
    return [
        {
            "component": "raw_target_return_exact",
            "required_inputs": "target_price,current_price generated by current model target engine",
            "source_file": SNAPSHOTS_FILE,
            "earliest_available_date": snap_start,
            "latest_available_date": snap_end,
            "can_be_reconstructed_from_prices_only": False,
            "requires_forecast_snapshots": True,
            "requires_model_generated_state": True,
            "reconstructability": "not reconstructable exactly before snapshots",
            "notes": "Exact raw target is model target/current price before signal adjustment; needs target engine replay or stored snapshots.",
        },
        {
            "component": "soft_exit_rule",
            "required_inputs": "prior selected tickers, current raw_target_return_exact",
            "source_file": PRODUCTION_PARITY_DAILY_FILE,
            "earliest_available_date": parity_start,
            "latest_available_date": parity_end,
            "can_be_reconstructed_from_prices_only": False,
            "requires_forecast_snapshots": True,
            "requires_model_generated_state": True,
            "reconstructability": "partially reconstructable",
            "notes": "Rule itself is simple, but depends on prior model selections and raw target sign.",
        },
        {
            "component": "volatility_target_22pct",
            "required_inputs": "prior strategy returns, target_volatility=22%, min/max exposure, max exposure change",
            "source_file": PRODUCTION_PARITY_DAILY_FILE,
            "earliest_available_date": parity_start,
            "latest_available_date": parity_end,
            "can_be_reconstructed_from_prices_only": False,
            "requires_forecast_snapshots": False,
            "requires_model_generated_state": True,
            "reconstructability": "fully reconstructable after candidate return series exists",
            "notes": "Exposure formula is deterministic once strategy returns exist.",
        },
        {
            "component": "exposure_cap_60",
            "required_inputs": "volatility target exposure",
            "source_file": "growth_candidate_paper_config.json",
            "earliest_available_date": parity_start,
            "latest_available_date": parity_end,
            "can_be_reconstructed_from_prices_only": False,
            "requires_forecast_snapshots": False,
            "requires_model_generated_state": False,
            "reconstructability": "fully reconstructable",
            "notes": "Fixed overlay cap; no data dependency beyond base exposure.",
        },
        {
            "component": "expected_return",
            "required_inputs": "target_price,current_price,time_to_target,signal_strength,regime/risk adjustments",
            "source_file": SNAPSHOTS_FILE,
            "earliest_available_date": snap_start,
            "latest_available_date": snap_end,
            "can_be_reconstructed_from_prices_only": False,
            "requires_forecast_snapshots": True,
            "requires_model_generated_state": True,
            "reconstructability": "partially reconstructable if full model pipeline is rerun on historical prices",
            "notes": "Not used directly by growth v2 selection once raw target exact is available, but part of snapshot lineage.",
        },
        {
            "component": "signal_strength",
            "required_inputs": "model diagnostics/features at decision date",
            "source_file": FEATURE_STORE_FILE,
            "earliest_available_date": feature_start,
            "latest_available_date": feature_end,
            "can_be_reconstructed_from_prices_only": "partial",
            "requires_forecast_snapshots": False,
            "requires_model_generated_state": True,
            "reconstructability": "partially reconstructable",
            "notes": "Growth ranking uses signal_strength as tie-breaker/support; many parts can be recomputed from prices but exact pipeline state matters.",
        },
        {
            "component": "regime_gate",
            "required_inputs": "SPY/QQQ/VIX/regime model outputs",
            "source_file": SNAPSHOTS_FILE,
            "earliest_available_date": snap_start,
            "latest_available_date": snap_end,
            "can_be_reconstructed_from_prices_only": "partial",
            "requires_forecast_snapshots": False,
            "requires_model_generated_state": True,
            "reconstructability": "partially reconstructable",
            "notes": "Growth v2 itself is raw-target based; regime data is still relevant for comparing to production champion.",
        },
        {
            "component": "forecast_calibration",
            "required_inputs": "historical forecast errors and evaluated labels",
            "source_file": "walk_forward_calibrated_forecasts.csv",
            "earliest_available_date": _source_date_range("walk_forward_calibrated_forecasts.csv")[0],
            "latest_available_date": _source_date_range("walk_forward_calibrated_forecasts.csv")[1],
            "can_be_reconstructed_from_prices_only": False,
            "requires_forecast_snapshots": True,
            "requires_model_generated_state": True,
            "reconstructability": "not required for growth champion v2",
            "notes": "Not active in Growth Champion v2; diagnostic/research layer only.",
        },
    ]


def dependency_audit() -> pd.DataFrame:
    out = pd.DataFrame(_component_rows())
    out.to_csv(OUT_DEPENDENCY, index=False)
    return out


def reconstructability(dependencies: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, row in dependencies.iterrows():
        component = row["component"]
        label = str(row["reconstructability"])
        if label.startswith("fully"):
            classification = "fully_reconstructable"
        elif label.startswith("partially") or "if full model pipeline" in label:
            classification = "partially_reconstructable"
        elif "not required" in label:
            classification = "not_required_for_growth_v2"
        else:
            classification = "not_reconstructable"
        rows.append(
            {
                "component": component,
                "classification": classification,
                "can_reconstruct_exact_pre_2022": bool(classification == "fully_reconstructable" and component in {"exposure_cap_60"}),
                "can_reconstruct_approx_pre_2022": bool(classification in {"fully_reconstructable", "partially_reconstructable"}),
                "price_only_possible": bool(component in {"volatility_target_22pct", "exposure_cap_60"}),
                "blocking_issue": "" if classification != "not_reconstructable" else "requires model-generated target snapshots or full historical pipeline replay",
                "notes": row.get("notes", ""),
            }
        )
    out = pd.DataFrame(rows)
    out.to_csv(OUT_RECONSTRUCT, index=False)
    return out


def historical_data_coverage() -> pd.DataFrame:
    snapshots = _dates(_read_csv(SNAPSHOTS_FILE))
    realized = _dates(_read_csv(REALIZED_FILE))
    trades = _dates(_read_csv(GROWTH_TRADES_FILE))
    if trades.empty or "ticker" not in trades.columns:
        tickers = sorted(snapshots["ticker"].dropna().astype(str).unique()) if "ticker" in snapshots.columns else []
    else:
        tickers = sorted(trades["ticker"].dropna().astype(str).unique())

    rows = []
    for ticker in tickers:
        snap_t = snapshots[snapshots.get("ticker", pd.Series(dtype=str)).astype(str).eq(ticker)].copy() if not snapshots.empty else pd.DataFrame()
        real_t = realized[realized.get("ticker", pd.Series(dtype=str)).astype(str).eq(ticker)].copy() if not realized.empty else pd.DataFrame()
        all_dates = snap_t["date"] if not snap_t.empty else pd.Series(dtype="datetime64[ns]")
        first_date = all_dates.min() if not all_dates.empty else pd.NaT
        last_date = all_dates.max() if not all_dates.empty else pd.NaT
        obs = int(len(all_dates))
        expected_obs = int(snapshots["date"].nunique()) if not snapshots.empty and "date" in snapshots.columns else obs
        missing_pct = float(max(0, expected_obs - obs) / expected_obs) if expected_obs else np.nan
        rows.append(
            {
                "ticker": ticker,
                "first_available_snapshot_date": first_date.strftime("%Y-%m-%d") if pd.notna(first_date) else "",
                "last_available_snapshot_date": last_date.strftime("%Y-%m-%d") if pd.notna(last_date) else "",
                "snapshot_observations": obs,
                "realized_return_observations": int(len(real_t)),
                "missing_data_pct_vs_snapshot_calendar": missing_pct,
                "sufficient_history_for_2022_replay": bool(pd.notna(first_date) and first_date <= pd.Timestamp("2022-01-03")),
                "sufficient_history_for_2020": bool(pd.notna(first_date) and first_date <= pd.Timestamp("2020-01-01")),
                "sufficient_history_for_2015": bool(pd.notna(first_date) and first_date <= pd.Timestamp("2015-01-01")),
                "sufficient_history_for_2010": bool(pd.notna(first_date) and first_date <= pd.Timestamp("2010-01-01")),
                "sufficient_history_for_2008": bool(pd.notna(first_date) and first_date <= pd.Timestamp("2008-01-01")),
            }
        )
    out = pd.DataFrame(rows)
    out.to_csv(OUT_COVERAGE, index=False)
    return out


def reconstruction_plan(dependencies: pd.DataFrame, coverage: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    snap_start, snap_end = _source_date_range(SNAPSHOTS_FILE)
    exact_start = snap_start or ""
    approximate_start = "requires_new_historical_pipeline_run"
    price_only_start = "depends_on_downloaded_price_history_not_available_as_snapshot"
    if not coverage.empty:
        tickers_2022 = int(coverage["sufficient_history_for_2022_replay"].sum())
        tickers_2020 = int(coverage["sufficient_history_for_2020"].sum())
    else:
        tickers_2022 = 0
        tickers_2020 = 0

    rows = [
        {
            "reconstruction_type": "exact_replay",
            "earliest_possible_start_date": exact_start,
            "feasible_before_2022": False,
            "methodology": "Use stored historical_forecast_snapshots target/current price and historical_realized_returns labels.",
            "requirements": "Existing model-generated snapshots for every decision date.",
            "limitations": "Cannot start before first snapshot date.",
        },
        {
            "reconstruction_type": "approximate_replay",
            "earliest_possible_start_date": approximate_start,
            "feasible_before_2022": "possible_if_raw_prices_and_full_model_pipeline_are_rerun",
            "methodology": "Download historical prices, truncate at each t, rerun current target engine and growth feature generator, then apply soft exit/vol target/cap.",
            "requirements": "Historical adjusted close for universe, current code compatibility, no live prices, no future CEDEAR point-in-time assumption.",
            "limitations": "Not exact production parity because current code/CEDEAR list may differ from historical state.",
        },
        {
            "reconstruction_type": "price_only_replay",
            "earliest_possible_start_date": price_only_start,
            "feasible_before_2022": "partial_only",
            "methodology": "Approximate raw target with price-derived momentum/target proxy, then apply soft exit/vol targeting/cap.",
            "requirements": "Price history only.",
            "limitations": "Does not reproduce raw_target_return_exact; should be labelled a different research model.",
        },
    ]
    plan = pd.DataFrame(rows)
    plan.to_csv(OUT_PLAN, index=False)

    exact_possible = bool(exact_start and pd.Timestamp(exact_start) <= pd.Timestamp("2022-01-03"))
    governance_class = "approximate_replay_possible"
    if exact_possible and tickers_2022 > 0:
        governance_class = "exact_replay_possible_from_2022_only"
    if tickers_2020 == 0:
        pre_2022_note = "No stored model-generated snapshots before 2022-01-03; exact replay before 2022 is not feasible locally."
    else:
        pre_2022_note = "Some local data appears before 2022, but exact growth snapshots still need verification."
    governance = pd.DataFrame(
        [
            {
                "classification": governance_class,
                "exact_replay_earliest_start": exact_start,
                "approximate_replay_earliest_start": approximate_start,
                "price_only_replay_earliest_start": price_only_start,
                "requested_2008_feasible_exact": False,
                "requested_2010_feasible_exact": False,
                "requested_2015_feasible_exact": False,
                "requested_2020_feasible_exact": False,
                "production_changed": False,
                "parameter_tuning": False,
                "governance_note": pre_2022_note,
            }
        ]
    )
    governance.to_csv(OUT_GOVERNANCE, index=False)
    return plan, governance


def run_phase_69() -> None:
    dependencies = dependency_audit()
    recon = reconstructability(dependencies)
    coverage = historical_data_coverage()
    plan, governance = reconstruction_plan(dependencies, coverage)

    print("\n===== FEATURE DEPENDENCY AUDIT =====")
    print(dependencies[["component", "earliest_available_date", "can_be_reconstructed_from_prices_only", "requires_forecast_snapshots", "requires_model_generated_state"]].to_string(index=False))

    print("\n===== RECONSTRUCTABILITY ANALYSIS =====")
    print(recon[["component", "classification", "can_reconstruct_exact_pre_2022", "can_reconstruct_approx_pre_2022", "price_only_possible"]].to_string(index=False))

    print("\n===== HISTORICAL DATA COVERAGE =====")
    print(f"tickers audited: {len(coverage)}")
    if not coverage.empty:
        print(f"tickers sufficient for 2022 replay: {int(coverage['sufficient_history_for_2022_replay'].sum())}")
        print(f"tickers sufficient for 2020 exact snapshot replay: {int(coverage['sufficient_history_for_2020'].sum())}")
        print(coverage.head(20).to_string(index=False))

    print("\n===== EARLIEST POSSIBLE START DATE =====")
    print(governance.to_string(index=False))

    print("\n===== RECONSTRUCTION PLAN =====")
    print(plan.to_string(index=False))

    print("\nFiles generated:")
    for p in [OUT_DEPENDENCY, OUT_RECONSTRUCT, OUT_COVERAGE, OUT_PLAN, OUT_GOVERNANCE]:
        print(f"- {Path(p).resolve()}")


if __name__ == "__main__":
    run_phase_69()
